// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from ":/integrations/supabase/client";

const g = globalThis as unknown as { __supabaseClient?: ReturnType<typeof createClient<Database>> };

export const supabase = g.__supabaseClient ?? (
  g.__supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
    auth: {
      persistSession: false,
      autoRefreshToken: true,
    },
  })
);
